In [1]:
import torch

After importing the needed library it is important to define some tensors. the cell below shows how to define a tensor

In [27]:
zTensor = torch.zeros(size=(32, 3, 64, 64), requires_grad=True)
theTensor = torch.tensor([1, 2, 3, 4, 5, 5, 5, 5])
oneTensor = torch.ones(size=(32, 3, 128, 128), requires_grad=True)
randTensor = torch.randn(size=(32, 3, 128, 128), requires_grad=True)

In [28]:
print(zTensor.shape)
print(theTensor.shape)
print(oneTensor.shape)
print(randTensor.shape)

torch.Size([32, 3, 64, 64])
torch.Size([8])
torch.Size([32, 3, 128, 128])
torch.Size([32, 3, 128, 128])


As it is shown in the prints it is really hard to define a tensor manually. zeros, ones, and rands are so useful in Neural Network creations. the torch creates the tensor in a shape we want and then fills it with zeros or ones or random numbers.

In [4]:
print(zTensor.ndim)
print(theTensor.ndim)
print(oneTensor.ndim)
print(randTensor.ndim)

4
1
4
4


I say all the time: "it is so important to find the shape first." shape of a matrix or tensor tells us that if we write down the matrix on paper, how many rows and columns it would have (assume it is a 2D matrix or tensor), but dimensions show that if it is 1D or 2D or else, the count of numbers appearing in the Shape shows the number of dimensions.

In [5]:
print(zTensor.dtype, theTensor.dtype, oneTensor.dtype, randTensor.dtype)

torch.float32 torch.int64 torch.float32 torch.float32


The prints show that when we use automated torch functions to create a tensor, it allocates float for that tensor in memory but when we specifictly fill the tensor with integer numbers it allocates int in memory

In [6]:
rand1 = torch.randn(size=(2, 2))
rand2 = torch. randn(size=(2, 2))
print(rand1)
print("-------------------")
print(rand2)

tensor([[ 0.3840,  0.3701],
        [-2.0034,  0.0994]])
-------------------
tensor([[-0.6844,  0.0502],
        [-1.2237,  0.0615]])


4 cells  bellow show 4 different operations applied on 2 tensors. all these 4 operators are working element-wise, but the 5th one is tensor multiplication or matmul operation which is not element-wise, obviously it works on tensors with same shape.

In [7]:
rand3 = rand1 + rand2
print(rand3)

tensor([[-0.3004,  0.4203],
        [-3.2271,  0.1609]])


In [8]:
rand3 = rand1 - rand2
print(rand3)

tensor([[ 1.0684,  0.3199],
        [-0.7797,  0.0380]])


In [9]:
rand3 = rand1 * rand2
print(rand3)

tensor([[-0.2628,  0.0186],
        [ 2.4516,  0.0061]])


In [10]:
rand3 = rand1 / rand2
print(rand3)

tensor([[-0.5610,  7.3699],
        [ 1.6372,  1.6174]])


In [11]:
rand3 = rand1 @ rand2
print(rand3)

tensor([[-0.7157,  0.0420],
        [ 1.2495, -0.0945]])


In [12]:
rand4 = torch.randn(size=(3, 2))
rand5 = torch.randn(size=(2, 3))
rand6 = torch.zeros(size=(3, 3))
print(rand4)
print("--------------------------")
print(rand5)
print("--------------------------")
print(rand6)


tensor([[-1.1865, -0.1518],
        [ 2.9259,  0.1697],
        [-2.1944,  0.9772]])
--------------------------
tensor([[-0.9117,  0.8482,  0.4240],
        [ 0.2210,  1.6507, -0.7028]])
--------------------------
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


The operator bellow shows the matmul, tensor multiplication. we should consider the tensor shapes,

In [13]:
rand6 = rand4 @ rand5
print(rand6)


tensor([[ 1.0482, -1.2569, -0.3964],
        [-2.6300,  2.7618,  1.1213],
        [ 2.2166, -0.2481, -1.6172]])


in case of using this operator we will get an Error.
because this operator wants to multiply element wise but both tensors are not
in the same shape

In [14]:
# rand6 = rand4 * rand5




In [35]:
oneReshaped = oneTensor.reshape(32, -1)
print(oneReshaped.shape)

torch.Size([32, 49152])


In [36]:
oneReshaped2 = oneReshaped.reshape(32, 3, 128, 128)
print(oneReshaped2.shape)

torch.Size([32, 3, 128, 128])


In [41]:
randTensorSqueezed = randTensor.unsqueeze(0)
print(randTensorSqueezed.shape)
randTensorReverted = randTensorSqueezed.squeeze()
print(randTensorReverted.shape)

torch.Size([1, 32, 3, 128, 128])
torch.Size([32, 3, 128, 128])


In [50]:
def describe_tensor(tensor):
  received = tensor
  print("The recieved tensor has ", received.shape, "shape")
  print("Also it is a ", received.ndim, "dimensional Tensor")
  print("We create a new tensor filled with random numbers")
  newTensor = torch.randn(size=received.shape)
  print("The element-wise multiplication of the recived and random is")
  result1 = newTensor * received
  print(result1[1])
  print("The element-wise division of the recived and random is")
  result2 = newTensor / received
  print(result2[1])
  print("Matrix Multiplication of these two would be like:")
  result3 = newTensor @ received
  print(result3[1])

  print("after Unsqeez it is:")
  receivedUnsqueezed = received.unsqueeze(0)
  print(receivedUnsqueezed.shape)
  print("after squeeze it is:")
  receivedSqueezed = receivedUnsqueezed.squeeze()
  print(receivedSqueezed.shape)
  if received.ndim == 4:
    receivedPermuted = received.permute(0, 3, 1, 2)
    print("after permute it is:")
    print(receivedPermuted.shape)


In [51]:
describe_tensor(randTensor)

The recieved tensor has  torch.Size([32, 3, 128, 128]) shape
Also it is a  4 dimensional Tensor
We create a new tensor filled with random numbers
The element-wise multiplication of the recived and random is
tensor([[[ 1.3408e-01, -1.2112e+00, -7.6387e-01,  ..., -2.6615e-01,
          -3.7828e+00, -3.1740e-01],
         [ 1.0122e-01, -1.2263e-01, -1.2302e+00,  ...,  2.7896e+00,
           2.0181e-02, -1.2662e-01],
         [ 3.3242e-02,  1.3878e+00,  8.8502e-02,  ..., -8.8735e-01,
           6.8968e-01,  3.0359e-01],
         ...,
         [ 8.1241e-01,  1.5224e+00, -2.6966e-01,  ..., -2.7706e+00,
           2.9400e-01,  3.2377e-01],
         [-8.2578e-03, -2.7536e-03,  8.2604e-01,  ..., -1.6577e-01,
           6.5291e-01, -2.0437e-01],
         [ 4.3277e-01, -2.7710e+00,  6.4688e-01,  ...,  2.5242e-01,
          -2.6159e-01,  5.5159e-02]],

        [[-1.9761e-02,  1.3997e-01, -3.0189e-01,  ..., -3.3406e+00,
          -2.2456e-01, -4.7606e-01],
         [ 7.8516e-03,  4.0084e-02, -8.126